env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:svelte/recommended
  - plugin:astro/recommended
  - prettier
overrides:
  - files:
      - "*.svelte"
    parser: svelte-eslint-parser
  - files:
      - "*.astro"
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions:
        - ".astro"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions:
    - ".svelte"
    - ".astro"
plugins:
  - "@typescript-eslint"
